//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resource.Data", typeof(Resource_Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Metal Charged.
        /// </summary>
        public static string Phases_Confirmation_HotMetalCharged {
            get {
                return ResourceManager.GetString("Phases_Confirmation_HotMetalCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Oxygen Blowing.
        /// </summary>
        public static string Phases_Confirmation_OxygenBlowingStart {
            get {
                return ResourceManager.GetString("Phases_Confirmation_OxygenBlowingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap Charged.
        /// </summary>
        public static string Phases_Confirmation_ScrapCharged {
            get {
                return ResourceManager.GetString("Phases_Confirmation_ScrapCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Materials -&gt; L1.
        /// </summary>
        public static string Phases_L1_ChargeMaterials {
            get {
                return ResourceManager.GetString("Phases_L1_ChargeMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Oxygen Blowing -&gt; L1.
        /// </summary>
        public static string Phases_L1_OxygenBlowingStart {
            get {
                return ResourceManager.GetString("Phases_L1_OxygenBlowingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygen Lance Parking -&gt; L1.
        /// </summary>
        public static string Phases_L1_OxygenLanceParking {
            get {
                return ResourceManager.GetString("Phases_L1_OxygenLanceParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Measurement -&gt; L1.
        /// </summary>
        public static string Phases_L1_TemperatureMeasurement {
            get {
                return ResourceManager.GetString("Phases_L1_TemperatureMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging Hot Metal.
        /// </summary>
        public static string Phases_Name_ChargingHotMetal {
            get {
                return ResourceManager.GetString("Phases_Name_ChargingHotMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging Materials.
        /// </summary>
        public static string Phases_Name_ChargingMaterials {
            get {
                return ResourceManager.GetString("Phases_Name_ChargingMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging Scrap.
        /// </summary>
        public static string Phases_Name_ChargingScrap {
            get {
                return ResourceManager.GetString("Phases_Name_ChargingScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygen Blowing.
        /// </summary>
        public static string Phases_Name_OxygenBlowing {
            get {
                return ResourceManager.GetString("Phases_Name_OxygenBlowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Addition.
        /// </summary>
        public static string Phases_Name_OxygenBlowing_MatAdd {
            get {
                return ResourceManager.GetString("Phases_Name_OxygenBlowing_MatAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        public static string Phases_Name_OxygenBlowingCorrection {
            get {
                return ResourceManager.GetString("Phases_Name_OxygenBlowingCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Measurement.
        /// </summary>
        public static string Phases_Name_TemperatureMasurement {
            get {
                return ResourceManager.GetString("Phases_Name_TemperatureMasurement", resourceCulture);
            }
        }
    }
}
