//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.239
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectOPCClient.MainGate {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Core.MainGate", ConfigurationName="MainGate.IMainGate", CallbackContract=typeof(DirectOPCClient.MainGate.IMainGateCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMainGate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Core.MainGate/IMainGate/Autentificate", ReplyAction="http://Core.MainGate/IMainGate/AutentificateResponse")]
        bool Autentificate(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Core.MainGate/IMainGate/PushEvent", ReplyAction="http://Core.MainGate/IMainGate/PushEventResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.ConverterBaseEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.SlagBlowingEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.ConverterAngleEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.AdditionsEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.HotMetalLadleEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.SteelAnalysisEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.ScrapEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.OffGasAnalysisEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.BlowingInterruptEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.TorkretingEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.ResetO2TotalVolEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.LanceEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.ReBlowingEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.BlowingEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.HeatingScrapEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.MixerAnalysisEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.OffGasEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.HeatChangeEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.IgnitionEvent))]
        void PushEvent(Core.BaseEvent baseEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Core.MainGate/IMainGate/Subscribe", ReplyAction="http://Core.MainGate/IMainGate/SubscribeResponse")]
        bool Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Core.MainGate/IMainGate/Unsubscribe", ReplyAction="http://Core.MainGate/IMainGate/UnsubscribeResponse")]
        bool Unsubscribe();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainGateCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Core.MainGate/IMainGate/OnEvent")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.ConverterBaseEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.SlagBlowingEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.ConverterAngleEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.AdditionsEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.HotMetalLadleEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.SteelAnalysisEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.ScrapEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.OffGasAnalysisEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.BlowingInterruptEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.TorkretingEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.ResetO2TotalVolEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.LanceEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.ReBlowingEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.BlowingEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.HeatingScrapEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.MixerAnalysisEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.OffGasEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.HeatChangeEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Converter.IgnitionEvent))]
        void OnEvent(Core.BaseEvent newEvent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainGateChannel : DirectOPCClient.MainGate.IMainGate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainGateClient : System.ServiceModel.DuplexClientBase<DirectOPCClient.MainGate.IMainGate>, DirectOPCClient.MainGate.IMainGate {
        
        public MainGateClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MainGateClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MainGateClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MainGateClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MainGateClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool Autentificate(string login, string password) {
            return base.Channel.Autentificate(login, password);
        }
        
        public void PushEvent(Core.BaseEvent baseEvent) {
            base.Channel.PushEvent(baseEvent);
        }
        
        public bool Subscribe() {
            return base.Channel.Subscribe();
        }
        
        public bool Unsubscribe() {
            return base.Channel.Unsubscribe();
        }
    }
}
