//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.MainGateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://NordSteeel.Core.MainGate", ConfigurationName="MainGateService.IMainGate")]
    public interface IMainGate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NordSteeel.Core.MainGate/IMainGate/Autentificate", ReplyAction="http://NordSteeel.Core.MainGate/IMainGate/AutentificateResponse")]
        bool Autentificate(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NordSteeel.Core.MainGate/IMainGate/PushEvent", ReplyAction="http://NordSteeel.Core.MainGate/IMainGate/PushEventResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Core.LanceEvent))]
        void PushEvent(Core.BaseEvent baseEvent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainGateChannel : Client.MainGateService.IMainGate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainGateClient : System.ServiceModel.ClientBase<Client.MainGateService.IMainGate>, Client.MainGateService.IMainGate {
        
        public MainGateClient() {
        }
        
        public MainGateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainGateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainGateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainGateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Autentificate(string login, string password) {
            return base.Channel.Autentificate(login, password);
        }
        
        public void PushEvent(Core.BaseEvent baseEvent) {
            base.Channel.PushEvent(baseEvent);
        }
    }
}
