//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources.UI", typeof(Resources_UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat number {0} not found..
        /// </summary>
        public static string FormBatchPreparation_HeatNumberNotFound {
            get {
                return ResourceManager.GetString("FormBatchPreparation_HeatNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected hot metal has incorrent input value..
        /// </summary>
        public static string FormBatchPreparation_HotMetal_Zero {
            get {
                return ResourceManager.GetString("FormBatchPreparation_HotMetal_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected scrap has incorrent input value..
        /// </summary>
        public static string FormBatchPreparation_Scrap_Zero {
            get {
                return ResourceManager.GetString("FormBatchPreparation_Scrap_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code cannot be empty..
        /// </summary>
        public static string FormDatabaseMaterialDefinition_Validation1 {
            get {
                return ResourceManager.GetString("FormDatabaseMaterialDefinition_Validation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed length is 64 characters..
        /// </summary>
        public static string FormDatabaseMaterialDefinition_Validation2 {
            get {
                return ResourceManager.GetString("FormDatabaseMaterialDefinition_Validation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Code cannot be empty..
        /// </summary>
        public static string FormDatabaseMaterialDefinition_Validation3 {
            get {
                return ResourceManager.GetString("FormDatabaseMaterialDefinition_Validation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed length is 16 characters..
        /// </summary>
        public static string FormDatabaseMaterialDefinition_Validation4 {
            get {
                return ResourceManager.GetString("FormDatabaseMaterialDefinition_Validation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed length is 1024 characters..
        /// </summary>
        public static string FormDatabaseMaterialDefinition_Validation5 {
            get {
                return ResourceManager.GetString("FormDatabaseMaterialDefinition_Validation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property must be selected..
        /// </summary>
        public static string FormDatabaseMaterialDefinition_Validation6 {
            get {
                return ResourceManager.GetString("FormDatabaseMaterialDefinition_Validation6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material with the same Code already exists..
        /// </summary>
        public static string FormDatabaseMaterialDefinition_Validation7 {
            get {
                return ResourceManager.GetString("FormDatabaseMaterialDefinition_Validation7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        public static string FormDatabaseSteelGrades_Validation1 {
            get {
                return ResourceManager.GetString("FormDatabaseSteelGrades_Validation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed length is 256 characters..
        /// </summary>
        public static string FormDatabaseSteelGrades_Validation2 {
            get {
                return ResourceManager.GetString("FormDatabaseSteelGrades_Validation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Grade  with the same Name already exists..
        /// </summary>
        public static string FormDatabaseSteelGrades_Validation3 {
            get {
                return ResourceManager.GetString("FormDatabaseSteelGrades_Validation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to run simulation?.
        /// </summary>
        public static string FormProcessedHeats_RunSimulation {
            get {
                return ResourceManager.GetString("FormProcessedHeats_RunSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add record.
        /// </summary>
        public static string UI_Defaults_BarButtonAdd {
            get {
                return ResourceManager.GetString("UI_Defaults_BarButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete record.
        /// </summary>
        public static string UI_Defaults_BarButtonDelete {
            get {
                return ResourceManager.GetString("UI_Defaults_BarButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert record.
        /// </summary>
        public static string UI_Defaults_BarButtonInsert {
            get {
                return ResourceManager.GetString("UI_Defaults_BarButtonInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected record?.
        /// </summary>
        public static string UI_Defaults_DeleteRecordQuestion {
            get {
                return ResourceManager.GetString("UI_Defaults_DeleteRecordQuestion", resourceCulture);
            }
        }
    }
}
